# Generated by Django 5.1.7 on 2025-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('COURS', 'Cours'), ('TD', 'TD'), ('TP', 'TP')], max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('has_projector', models.BooleanField(default=False)),
                ('computers_count', models.IntegerField(default=0)),
            ],
        ),
    ]
